global:
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_from: "alertmanager@rmit.edu.vn"
  smtp_auth_username: "trankhoa758@gmail.com"
  smtp_auth_password: "elrbypijieiufoan"

route:
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: "email"

receivers:
  - name: "email"
    email_configs:
      - to: "tkhoa65@gmail.com"
