version: "3.8"

services:
  web:
    image: s3847766/cosc2767-rmit-store
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80" # Host:Container
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.role == store
    depends_on:
      - db
    networks:
      - rmit-store_monitoring

  db:
    image: s3847766/random-team-1-mariadb-prod
    environment:
      MYSQL_ROOT_PASSWORD: rmit_password
      MYSQL_DATABASE: rmit_store_db
      MYSQL_USER: db_admin
      MYSQL_PASSWORD: rmit_password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "8083:3306"
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.role == store
    networks:
      - rmit-store_monitoring

  prometheus:
    image: s3847766/random-team-1-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports:
      - "9090:9090"
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.role == store
    networks:
      - rmit-store_monitoring

  grafana:
    image: s3847766/random-team-1-grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.role == store
    networks:
      - rmit-store_monitoring

  alertmanager:
    image: s3847766/random-team-1-alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.role == store
    networks:
      - rmit-store_monitoring

  node_exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.role == store
    networks:
      - rmit-store_monitoring

networks:
  rmit-store_monitoring:
    driver: overlay

volumes:
  dbdata:
