#   RMIT University Vietnam
#   Course: COSC2767 Systems Deployment and Operations
#   Semester: 2023B
#   Assessment: Assignment 3
#   Author: Random Team 1
#   ID: 3847766
#   Created date: 22/1/2024
#   Last modified: 22/1/2024
#   Acknowledgement: Tutorial, ChatGPT, Stackoverflow, AWS Documentation

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "apache"
    metrics_path: "/server-status"
    static_configs:
      - targets: ["34.234.46.52:80"]
    scheme: http # or https if your server uses SSL
